### ISSUE TITLE
Adapt to libfmt 9.x

### ISSUE THREAD

**Issue by morxa** [morxa/tacos#182]
[libfmt9](https://github.com/fmtlib/fmt/releases/tag/9.0.0) changed how libfmt interacts with ostreams:
> Disabled automatic std::ostream insertion operator (operator<<) discovery when fmt/ostream.h is included to prevent ODR violations. You can get the old behavior by defining FMT_DEPRECATED_OSTREAM but this will be removed in the next major release. Use fmt::streamed or fmt::ostream_formatter to enable formatting via std::ostream instead.

This currently causes build failures in our code base.

**Comment by morxa** [comment]
One possible approach would be to completely get rid of ostream operators and rely on `fmt::format` and `spdlog` instead.

**Comment by modass** [comment]
I am not sure, whether I like this direction of development (on the side of libfmt), I believe ostream operators are a suitable way of generating output in a standardized way that is known and accessible to everyone. If we now get rid of ostream operators, we impose this on potential users as well, right? Furthermore, conceptually the difference between writing an ostream operator's body and the body of a custom formatter is almost zero, is that true?
