### ISSUE TITLE
MTL set member semantics vs single event semantics

### ISSUE THREAD

**Issue by morxa** [morxa/tacos#41]
We currently mix two kinds of MTL semantics, which differ in the satisfaction of atomic propositions.
1. "Member semantics" where an atomic proposition is satisfied if it is member of sigma_i
2. "Single event semantics" where an atomic proposition is satisfied if it is equal to sigma_i

Those two are equivalent as they can be translated into each other, but we should stick to one.

**Comment by modass** [comment]
Design decision: Single-event semantics.

**Comment by morxa** [comment]
With #130, both types of semantics are possible.
